### ISSUE TITLE
Suggest mentioning installing Overview locally via Docker can dominate existing setup

### ISSUE THREAD

**Issue by jerryhall** [overview/overview-local#28]
Being a noob to Docker I jumped right in and installed Overview Local in under :30 mins on my existing Ubuntu 20.04. I'm a Docker convert. Yow!

What I hadn't realized is that it would (by all appearances) take over the server. E.g. when I couldn't get my existing site working and grepped the ports, nearly every port was being used by Docker or Overview. 

That's a real messy way of me asking that you might consider suggesting to us noobs that one should install Overview on its own droplet or instance. Please skip the idea if this is Docker-101 and should've been known before diving in.

Thank you! I love Overview and am excited to give it a shot. I do appreciate this project very much!

**Comment by adamhooper** [comment]
That's a great point. Indeed, overview-local uses ports 9000 and 3000-3010 on localhost.

Here are some ways around it:

*1. don't publish ports*

Instead of accessing at localhost:9000, Overview could be at http://172.19.0.3:9000 or some other randomly-generated address. This would leave localhost unimpeded.

Three problems would remain:

1. Each time you start Overview, it'll be at a different address.
2. This can only work on Linux. Docker for Windows (and I think Mac) won't let you address Docker containers by IP address.
3. We'd need to run some SQL commands on startup to tell Overview its plugins' addresses have changed.

*2. make ports configurable*

We could let you set custom ports in `overview.env`.

Only one problem would remain: we'd need to run some SQL commands on startup to tell Overview its plugins' addresses have changed. (Or we'd need to document the problem.)

*3. use a virtual machine*

This is what you're suggesting. Probably the simplest approach.

**Comment by adamhooper** [comment]
@jerryhall I've documented the ports in the README. After pondering the other options, I don't think they're worth pursuing:

* Most people wouldn't be able to benefit (Windows/Mac users), so a new feature would be an obstacle.
* The users who _would_ be able to benefit from one of these features -- like you -- are expert enough to find other avenues (like a VM or a custom `docker-compose.yml`).

Please let me know if you think I'm wrong about my assessment. I'll help you get set up!
